site_name: My projects
site_author: Adam Biela

site_url: https://AdamoxB.github.io/ds_ai_portfolio/
site_description: >-
    My portfolio of Data Science and AI projects!

repo_name: AdamoxB/ds_ai_portfolio
repo_url: https://github.com/AdamoxB




# -- Theme ------------------------------------------------------------------
theme:
  # Wybierz sw√≥j motyw (np. material, readthedocs ‚Ä¶)
  name: material            # ‚Üê mo≈ºesz zmieniƒá na inny
  # custom_dir: custom
  logo: images/logo_portfolio.png # podaj w≈Çasny plik PNG/JPG
  favicon: images/logo_portfolio.png   # logo w zak≈Çadce przeglƒÖdarki 


  features:

    - toc.follow
    # - toc.integrate 
    - navigation.top

    - navigation.tabs
    - navigation.tabs.sticky

    - navigation.instant   # optional extras you already have
    - search.highlight
    - content.code.annotate
    - image.zoom          # Material‚Äôs built‚Äëin zoom feature

    - content.code.annotate
    - content.code.copy




  # --- kolory i kontrast ---------------------------------------------
  palette:
    # Palette toggle for automatic mode
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode
    - scheme: slate         # ciemny tryb (teraz domy≈õlny)
      primary: blue-grey
      accent: light-blue
      toggle:
        icon: material/weather-sunny
        name: Tryb jasny
    - scheme: default        # jasny tryb
      primary: teal       # g≈Ç√≥wny kolor
      accent: pink          # akcent
      toggle:
        icon: material/weather-night
        name: Tryb ciemny



  # --- czcionki -------------------------------------------------------
  font:
    text: Roboto
    code: Fira Code

  # --- ikona i logo (opcjonalne) --------------------------------------
  icon:
    repo: material/github   # w zak≈Çadce ‚Äûrepo‚Äù pojawi siƒô GitHub
 


plugins:
  # - mermaid:
  - mermaid2
  - search                 # core search plugin
  - glightbox:
      touchNavigation: true
      loop: false
      autoplay: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        # - custom-skip-class-name
        - skip-lightbox
      auto_themed: true
      auto_caption: true
      caption_position: bottom
      background: white
      shadow: true
      manual: false

  # Optional: configure Mermaid settings
  # e.g., enable theme, etc.

  # pip install mkdocs-image-zoom   # or pipx, poetry, etc.#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # - image-zoom             # <‚Äî this plugin does the heavy lifting


# --- dodatkowe zasoby -------------------------------------------------
extra_css:
  # - css/extra.css          # w≈Çasne regu≈Çy CSS
  # - css/style.cs
  - css/custom.css
  - css/secondary.css          # styl przycisku i zmiany tematu
  - css/centered-captions.css   # ≈õcie≈ºka wzglƒôdna od katalogu g≈Ç√≥wnego projektu

extra_javascript:
  # - js/custom.js           # je≈õli potrzebujesz JS (np. scrollspy)
  # - https://unpkg.com/mermaid@10.9.0/dist/mermaid.min.js
  # - js/mermaid-init.js 
  - js/secondary.js            # logika prze≈ÇƒÖczania
  - js/zoom.js

markdown_extensions:
  # - toc:
  #     permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.blocks.caption  # optional, for captions
  - attr_list        # ‚Üí add HTML attributes to Markdown elements
  - meta
  # - md_in_html# blokuje mermaid
  # - admonition
  - tables           # ‚Üí GitHub‚Äëstyle tables (and a few optional tweaks)

  - pymdownx.superfences
  - admonition
  - pymdownx.details
  # - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.tabbed
  - toc:
      permalink: true




nav:
  - Home Page: index.md

  - "My projects": 
    - "Previous projects":
        - SemanticAudioNotes: SemanticAudioNotes/index.md
        - My Chat GPT: My_Chat_GPT/index.md
        - Gapmind_Data_Dashboard: Gapmind_Data_Dashboard/index.md
        - ds_toolbox: ds_toolbox/index.md
        - Data_Explorer‚ÄìPyCaret: Data_Explorer‚ÄìPyCaret/index.md
        - Analysis_of_Key_Variables_in_Data_Sets: Analysis_of_Key_Variables_in_Data_Sets/index.md
        - Welcome Survey Clustering App pipeline: welcome_survey_clustering_pipeline/index.md
        - Short Crime Story Generator üìñ: AI_Short_Crime_Story_Generator/index.md
        - üé• Watch YouTube Videos - No Ads : Watch_YouTube_Videos‚ÄìNo_Ads/index.md
        - "AI_Data_Visualizer" : AI_Data_Visualizer/index.md
        - "Current projects":
            - "Short Crime Story Generator üìñ": AI_Short_Crime_Story_Generator/index.md
            - "AI_Data_Visualizer" : AI_Data_Visualizer/index.md
  - Plans: PLANS/index.md
  - Other_topics:
    - Example_to deploy_nice_pojects_Visualization_&_architecture...: Others/Project_visuals.md

      # - Iris: iris/index.md
      # - Titanic: titanic/index.md
  # - LLM TOPIC: LLM.md
      # - Explore AI on Radeon Today
      # - https://www.amd.com/en/products/graphics/radeon-ai.html#tabs-a538c331da-item-3d078efef9-tab
      
      
      # - RAG
      # - https://www.amd.com/en/blogs/2024/how-to-enable-rag-retrieval-augmented-generation-.html



